server.port=8080
server.address=0.0.0.0

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nalamai_db
spring.datasource.username=postgres
spring.datasource.password=Bala@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Security - disable default security for local development testing
spring.security.user.name=admin
spring.security.user.password=admin
